### ISSUE TITLE
I can't import fsaverage Desikan atlas into netplotbrain

### ISSUE THREAD

**Issue by npdrbong** [wiheto/netplotbrain#73]
netplotbrain.plot(nodes={'template':'fsaverage','atlas': 'Desikan2006', 'resolution':1},
                  template='fsaverage',
                  template_style=None,
                  view='S',
                  node_type='parcels',
                  node_alpha=1,
                  node_color='tab20c',
                  arrowaxis=None,
                  subtitles='Parcels',
                  fig=fig, ax=ax)
                  
    
I expected to download from templateflow, but it doesn't work

**Comment by wiheto** [comment]
Hi, 

1. Surface templates do not work at the moment, which is probably one of the problems. 
2. Please post actual errors instead of saying "it doesn't work"
3. If you just want to download the atlast, check out the python package tepmlateflow (templateflow.api) which does the downloading (and is what netplotbrain used). 

Closing this now, but feel free toreopen if I misunderstod somehting
